version: '3.9'
services:

  redis:
    image: redislabs/redismod
    container_name: redis
    restart: always
    ports:
      - "6379"

  redis-ui:
    container_name: redis-ui
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    ports:
      - "8081:8081"

  mhchan:
    container_name: mhchan
    build:
      context: .
      dockerfile: src/Dockerfile
    environment:
      DOTNET_REDIS__HOST: redis
      DOTNET_REDIS__PORT: 6379
      DOTNET_DISCORD__TOKEN: MTA2ODY5NjkyNTU2MzUxOTA5Ng.GI8bap.osUJiivbWwmva_yvEZpslVp_VHxy3fFP_2-5lY
      DOTNET_DISCORD__GUILD: 1068697076323602503
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - redis
      - redis-ui
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 2
        window: 120s
