services:
  redis:
    image: redis/redis-stack
    container_name: redis
    restart: always
    environment:
      REDIS_ARGS: --appendonly yes --maxmemory 256Mb
    ports:
      - 6379:6379
      - 8001:8001
  miha:
    image: miha:dev
    container_name: miha
    restart: always
    build:
      context: ./
      dockerfile: ./src/Dockerfile
    environment:
      DOTNET_REDIS__HOST: redis
      DOTNET_REDIS__PORT: 6379
      DOTNET_DISCORD__TOKEN: '----'
      DOTNET_DISCORD__GUILD: 1068697076323602503
    ports:
      - "8000:8000"
    depends_on:
      - redis
