name: Build - Push
on:
  release:
    types: [published]
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

    - uses: actions/checkout@v3

    - uses: docker/setup-buildx-action@v2

    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    # push: <branch-name>-long-sha, edge
    # release: v1.0.0, latest 
    - id: meta
      uses: docker/metadata-action@v4
      with:
        flavor: latest=false
        images: miha
        tags: |
          type=sha,format=long,event=branch
          type=edge,event=branch
