name: Build - Push
on:
  release:
    types: [published]
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

    - uses: actions/checkout@v3

    - uses: docker/setup-buildx-action@v2

    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - id: meta
      uses: docker/metadata-action@v4
      with:
        flavor: latest=auto
        images: miha
        tags: |
          # on branch push
          type=sha,format=short,prefix={{branch}}-,event=branch
          # on any push to main branch
          type=edge,branch=main,event=branch
          # on tag / release
          type=semver,pattern={{raw}},event=tag
